version: '3'
services:

  # The Application
  app:
    build:
      context: ./app/
      dockerfile: app.Dockerfile
    working_dir: /var/www
    volumes:
      - ./app/:/var/www/public

  # The Web Server
  web:
    build:
      context: ./web/
      dockerfile: web.Dockerfile
    working_dir: /var/www
    volumes:
      - ./web/:/var/www/
      - ./app/:/var/www/public
    ports:
      - 8081:80

volumes:
  dbdata: